// website/src/components/LeafletMap.vue
<template>
  <div class="container">
    <div id="mapContainer" class="mapContainer"></div>
  </div>
</template>

<script lang="ts">
import { defineComponent, unref } from "vue";

/* eslint-disable @typescript-eslint/no-explicit-any */
import "leaflet/dist/leaflet.css";
import { Map } from "leaflet/src/map";
import { Marker } from "leaflet/src/layer/marker/Marker";
import { TileLayer } from "leaflet/src/layer/tile/TileLayer";
import { Tooltip } from "leaflet/src/layer/Tooltip";
import { latLng } from "leaflet";

import { useData } from "../store/useData";

// fix "Uncaught TypeError: this._map is null" when zooming
(Tooltip.prototype as any)._updatePosition = function () {
  if (!this._map || !this._latlng) return;
  var pos = this._map.latLngToLayerPoint(this._latlng);
  this._setPosition(pos);
};
(Tooltip.prototype as any)._animateZoom = function (e: any) {
  if (!this._map || !this._latlng) return;
  var pos = this._map._latLngToNewLayerPoint(this._latlng, e.zoom, e.center);
  this._setPosition(pos);
};

export default defineComponent({
  name: "LeafletMap",
  setup() {
    const { point, lat, lon, tooltip } = useData();
    return { point, lat, lon, tooltip };
  },
  data() {
    return {
      map: undefined as unknown as Map,
    };
  },
  watch: {
    point() {
      this.updateMarker();
    },
  },
  mounted() {
    const lat = unref(this.lat);
    const lon = unref(this.lon);
    if (!lat || !lon) {
      return;
    }
    this.map = new Map("mapContainer").setView([lat, lon], 16) as Map;
    new TileLayer("https://{s}.tile.osm.org/{z}/{x}/{y}.png", {
      attribution:
        '&copy <a href="https://osm.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(this.map as Map);
    this.updateMarker();
  },
  methods: {
    updateMarker(): void {
      if (this.point === undefined) {
        return;
      }
      const _latlng = latLng(this.point);
      this.map.setView(_latlng);
      const tooltip = this.tooltip;
      tooltip === ""
        ? new Marker(_latlng).addTo(this.map as Map)
        : new Marker(_latlng)
            .bindTooltip(tooltip)
            .openTooltip()
            .addTo(this.map as Map);
    },
  },
});
</script>

<style scoped>
.mapContainer {
  width: 100%;
  height: 400px;
}
</style>

// django/static/js/src/components/LeafletMap.jsx
import React, { Component } from "react";
import ReactDOM from "react-dom";
import { Map, TileLayer, Marker, Popup } from "react-leaflet";

// require style and marker pngs
import "leaflet/dist/leaflet.css";
require('leaflet/dist/images/marker-icon-2x.png')
require('leaflet/dist/images/marker-icon.png')
require('leaflet/dist/images/marker-shadow.png')


export default class Leafletmap extends Component {
  constructor(props) {
    super(props);

    this.state = {
      lat: 37.7749,
      lng: -122.4194,
      zoom: 13,
    };
  }
  render() {
    const data = {
      "position": [47, 12],
      "displayName": "haha"
    }
    return (
      <Map
        center={data.position}
        zoom={14}
        style={{ width: "50%", height: "900px" }}
      >
        <TileLayer
          attribution='&copy <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
        />
        <Marker position={data.position}>
          <Popup>{data.displayName}</Popup>
        </Marker>
      </Map>
    );
  }
}
const wrapper = document.getElementById("leaflet_map");
wrapper
  ? ReactDOM.render(
      <Leafletmap data='{"displayName": "haha", "lat": 11, "lon": 10}' />,
      wrapper
    )
  : false;
